### PR TITLE
Add support for in the wild videos - using TRAM for SMPL/Camera estimation

### PR DESCRIPTION
**Pull request by gt732**
Hi,

I added a new data loader that can process SMPL/Camera parameters generated by [TRAM](https://github.com/yufu-wang/tram) and apply the animations to a 3D avatar. Please let me know if you would like any modifications. I did not update the README with instructions, leaving that to you in case you prefer a specific format. However, I can update it if needed.

Users will need to download and install TRAM and use it on their own videos. Once the estimation is complete, they just need to add the poses/camera files to the following folders:

Future updates I will try to add support for multiple people but for now it is focused on a single person.

```
custom_motion/
└── tram
    ├── animation
    │   └── hps_track_0.npy
    └── camera
        └── camera.npy
```

and then run the new script

```bash
bash scripts/inference_tram.sh
```

results using the pre trained GOKU and the example video from TRAM

https://github.com/user-attachments/assets/956541da-5c13-42b6-80c6-7a5e7e395d1a

Thanks!!

### CODE REVIEW

**Comment by Yukun-Huang** [comment]
Congrats! Thank you for implementing this important feature! I need some time to try it out before merge if you don't mind. Btw, do you think it would be better if TRAM could be integrated as a [submodule](https://gist.github.com/gitaarik/8735255) into DeamWaltz-G, so that users only have to clone the repo once and run a single script?

**Comment by baopmessi** [comment]
@gt732 Thank you for implementing this feature, can you implement overlay character on background of a video.

**Comment by gt732** [comment]
@Yukun-Huang Yes, adding it as a submodules and cloning it into a thirdparty folder should work. I have not tried running TRAM in the save python env as dreamwaltz. I ran it inside a docker container.

https://github.com/yufu-wang/tram/issues/10

I can test running it together with dreamwaltz.

@baopmessi There is a ton of methods for inpainting. The method I use is with comfyui workflow. 

https://openart.ai/workflows/cgtips/comfyui---propainter_object-removal/ZvP85nmaLbYIAq1rQVVE

**Comment by gt732** [comment]
Hi, I will be closing this request. After further testing the tram method is not reliable enough. It does not work on every video and needs tuning.

I’m looking into more better methods, once I find one I’ll open a new PR.

Thanks

**Comment by Yukun-Huang** [comment]
> Hi, I will be closing this request. After further testing the tram method is not reliable enough. It does not work on every video and needs tuning.
> 
> I’m looking into more better methods, once I find one I’ll open a new PR.
> 
> Thanks

Hi @gt732 Would you mind share some failure cases? The Goku example you showed earlier looks good.

**Comment by gt732** [comment]
@Yukun-Huang Reopening this again, the cause for the bad results during my testing was because I forgot to add the --static_camera argument here https://github.com/yufu-wang/tram/blob/0b1d84401d0843cc7f3fcae60ee9582277fc0316/scripts/estimate_camera.py#L17

I tried without the flag and could not figure out how to get it to work properly with dreamwaltz. This is due to my lack of understanding in computer vision (new to this field). Adding the static_camera argument even though the camera is moving in the video still produces good results. The code is still valid.

Results using another video from the wild.

https://github.com/user-attachments/assets/dc355a56-7fd9-437d-b03c-c9e7cb8223b6

If someone more knowledgeable in computer vision can adjust the code to work without the argument and DRIOD-SLAM results then please assist. If not the only way I was able to get it working was with adding that argument.

**Comment by Yukun-Huang** [comment]
I tried the code and it seems that the camera (world) coordinate systems of tram and dreamwaltz-g have different definitions. Some conversion code needs to be added. I will try to fix it when I have time.

**Comment by gt732** [comment]
> I tried the code and it seems that the camera (world) coordinate systems of tram and dreamwaltz-g have different definitions. Some conversion code needs to be added. I will try to fix it when I have time.

Thanks for your input and time!

**Comment by Yukun-Huang** [comment]
Hi @gt732, I think I figured out how to make tram compatible with dreamwaltz-g without the `static_camera` argument. The smpl parameters estimated by tram is already camera-relative, so `pred_cam_R` and `pred_cam_T` from `camera.npy` are actually not needed.

Would you mind sharing the inpainted version of this example video (with the human removed) with me? Then we can upload it to the repo and provide an example video for everyone.

https://github.com/user-attachments/assets/c87928ec-4b99-40c0-a3de-e6c247b76690

**Comment by gt732** [comment]
@Yukun-Huang Nice!! Ty for taking the time to troubleshoot this. Here is the version with the human removed.

https://github.com/user-attachments/assets/b952707d-b358-4af7-9849-fba1ad72bf87

**Pull request merged**
